# pretend we're building C
language: c
compiler:
  - gcc
env:
  - VALAC=valac-0.30
before_install:
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ${VALAC}
before_script:
  - autoreconf -if
