# default 12.04 is ancient, use trusty instead
dist: trusty
# pretend we're building C
language: c
compiler:
  - gcc
env:
  - VALAC=valac-0.32
before_install:
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ${VALAC} valac
  - sudo apt-get install -qq libgirepository1.0-dev
  - sudo apt-get install -qq gir1.2-gee-0.8 libgee-0.8-dev
  - sudo apt-get install -qq gir1.2-json-1.0 libjson-glib-dev
  - sudo apt-get install -qq gir1.2-notify-0.7 libnotify-dev
  - sudo apt-get install -qq gir1.2-atspi-2.0 libatspi2.0-dev
  - sudo apt-get install -qq gir1.2-gtk-3.0 libgtk-3-dev
before_script:
  - autoreconf -if
script:
  - ./configure && make V=1
